version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./:/home/gradle/project:cached
      - ~/.gradle:/home/gradle/.gradle
    command: ./gradlew bootRun --no-daemon
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/brickstore_dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: brickstore_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
